name: generate ascii Artwork

on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: |
        cowsay -f dragon "RUN for cover, I'm a Dragon....RAWR" > dragon.txt
        chmod +rw dragon.txt

    - name: Upload Dragon Text File
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon Text File
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
        path: .

    - name: Ensure dragon.txt exists
      run: test -f dragon.txt

    - name: Text File Exists Before Checking
      run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon Text File
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
        path: .

    - name: Read File
      run: cat dragon.txt

    - name: Deploy
      run: echo "Deploying ... .. ."
