name: Exploring Variables and Secrets

on:
  push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: kennykenny02
    IMAGE_NAME: github-actions-ninx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      env:
        DOCKER_PASSWORD: Naija123@
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      
    - name: Docker Publish
      run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: docker run $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest