name: Workflow Filters and Activities

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '!feature/*'    # ignore push starting with feature using !

  pull_request:
    types:
      - opened
      - closed
    paths-ignore:     # workflow will not run when a pull request includes only README.md
      - README.md
    branches:
      - main    # configures your workflow to only run on pull requests that target specific branches

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo "this workflow/job/step is executed for event type - ${{ github.event_name }}"