name: Workflow Filters and Activities

on:
  workflow_dispatch:
  push:
    branches:
        - main
        - '!feature/*'    # ignore push starting wit feature using !

pull_reques:
  types:
    - opened
    - closed
  paths-ignore:     # workflow will on run when a pull request that includes a change on any file README.md
     - README.md
    branches:
     - main    # configures your workflow to only run on pull requests that target specific branches

job:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type - ${{ github_event_name }}